/*
define(function () {
    var sidePop={};
    sidePop.addMenu=['<form id="addMpanel" class="form-horizontal">',
        '    <div class="form-group form-group-sm" style="margin: 15px 0px">',
        '        <label class="control-label col-sm-4"><i class="required">*</i>菜单名称</label>',
        '        <div class="col-sm-7">',
        '            <input name="" type="text" class="form-control">',
        '        </div>',
        '    </div>',
        '            <div class="form-group form-group-sm" style="margin: 15px 0px">',
        '                    <label class="control-label col-sm-4"><i class="required">*</i>上级菜单</label>',
        '                    <div class="col-sm-7">',
        '                            <select class="form-control">',
        '                                    <option>无</option>',
        '                                    <option>用户管理</option>',
        '                                </select>',
        '                        </div>',
        '                </div>',
        '            <div class="form-group form-group-sm" style="margin: 15px 0px">',
        '                    <label class="control-label col-sm-4">页面路径</label>',
        '                    <div class="col-sm-7">',
        '                            <input name="" type="text" class="form-control">',
        '                        </div>',
        '                </div>',
        '            <div class="form-group form-group-sm" style="margin: 15px 0px">',
        '                        <label class="control-label col-sm-4">菜单图标</label>',
        '                        <div class="col-md-3">',
        '                                <div class="" style="width: 55px;height: 55px;border: 1px solid lightgray;text-align: center;vertical-align: center;padding-top: 8px">',
        '                                        <i class="fa fa-user-o fa-2x"></i>',
        '                                        <a onclick="editIcon()" href="javascript:;" style="display: block;font-size: 12px;background-color: lightgray">修改图标</a>',
        '                                    </div>',
        '                            </div>',
        '                    </div>',
        '            <div class="form-group form-group-sm" style="margin: 15px 0px">',
        '                    <label class="control-label col-sm-4">备注</label>',
        '                    <div class="col-sm-7">',
        '                            <textarea class="form-control"></textarea>',
        '                        </div>',
        '                </div>',
        '            <div class="form-group" style="padding-left: 120px;margin: 15px 0px">',
        '                    <button id="doAdd" type="submit" class="btn btn-danger" style="margin-right: 30px">提交</button>',
        '                    <button name="doCancel" type="button" class="btn btn-default">取消</button>',
        '            </div>',
        '</form>'].join("");
    return sidePop;
})*/
